robot_description_planning:
  joint_limits:
    joint0:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 2.0
    joint1:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 2.0
    joint2:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 2.0
    joint3:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 3.0
    joint4:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 3.0
