move_group:
  ros__parameters:
    planning_plugin: ompl_interface/OMPLPlanner
    request_adapters: >-
      default_planner_request_adapters/AddTimeOptimalParameterization
      default_planner_request_adapters/ResolveConstraintFrames
      default_planner_request_adapters/FixWorkspaceBounds
      default_planner_request_adapters/FixStartStateBounds
      default_planner_request_adapters/FixStartStateCollision
      default_planner_request_adapters/FixStartStatePathConstraints
    start_state_max_bounds_error: 0.1
    moveit_manage_controllers: true
    trajectory_execution.allowed_execution_duration_scaling: 2.0
    trajectory_execution.allowed_goal_duration_margin: 0.5
    trajectory_execution.allowed_start_tolerance: 0.01
    publish_planning_scene: true
    publish_geometry_updates: true
    publish_state_updates: true
    publish_transforms_updates: true
